using '../main.bicep'

param resourceGroupName = 'rg-blazor-entra-dev'
param location = 'australiaeast'
param environmentName = 'dev'
param appNamePrefix = 'blazorentradev'
param githubOrg = 'hemantshelar'
param githubRepo = 'blazor-entra-azure-fic-sample'
param githubRef = 'refs/heads/main'
param appServiceSku = 'B1'
param linuxFxVersion = 'DOTNETCORE|10.0'
param azureAdTenantId = ''
param azureAdClientId = ''
param azureAdDomain = ''
