using '../main.bicep'

param resourceGroupName = 'rg-blazor-entra-prod'
param location = 'australiaeast'
param environmentName = 'prod'
param appNamePrefix = 'blazorentraprod'
param githubOrg = 'YOUR_GITHUB_ORG'
param githubRepo = 'YOUR_REPO_NAME'
param githubRef = 'refs/heads/main'
param appServiceSku = 'P1v3'
param linuxFxVersion = 'DOTNETCORE|10.0'
param azureAdTenantId = ''
param azureAdClientId = ''
param azureAdDomain = ''
